// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD68MykmZxzaDMu5K5osuyN5xrzDw7PL-E',
    appId: '1:607674212285:web:f527be216eb1f25e507cd4',
    messagingSenderId: '607674212285',
    projectId: 'studymate-4885a',
    authDomain: 'studymate-4885a.firebaseapp.com',
    storageBucket: 'studymate-4885a.firebasestorage.app',
    measurementId: 'G-198ZMW7HQF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQzS-JxEWn6-e-RWwCmPaEkSIA-X6rADI',
    appId: '1:607674212285:android:791ec1e33137b1ab507cd4',
    messagingSenderId: '607674212285',
    projectId: 'studymate-4885a',
    storageBucket: 'studymate-4885a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKKGmbyQoJPlwX1vevUlyvWjqDspKYqY4',
    appId: '1:607674212285:ios:18a8076faf6c2f69507cd4',
    messagingSenderId: '607674212285',
    projectId: 'studymate-4885a',
    storageBucket: 'studymate-4885a.firebasestorage.app',
    iosClientId: '607674212285-cd7fjg66fp0asue7efr6b0gsc0gjb139.apps.googleusercontent.com',
    iosBundleId: 'com.example.myFirstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKKGmbyQoJPlwX1vevUlyvWjqDspKYqY4',
    appId: '1:607674212285:ios:18a8076faf6c2f69507cd4',
    messagingSenderId: '607674212285',
    projectId: 'studymate-4885a',
    storageBucket: 'studymate-4885a.firebasestorage.app',
    iosClientId: '607674212285-cd7fjg66fp0asue7efr6b0gsc0gjb139.apps.googleusercontent.com',
    iosBundleId: 'com.example.myFirstApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD68MykmZxzaDMu5K5osuyN5xrzDw7PL-E',
    appId: '1:607674212285:web:ecbc395b35399899507cd4',
    messagingSenderId: '607674212285',
    projectId: 'studymate-4885a',
    authDomain: 'studymate-4885a.firebaseapp.com',
    storageBucket: 'studymate-4885a.firebasestorage.app',
    measurementId: 'G-B4QKLM5H5B',
  );
}
